/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6c139613824de2e356a56beb3a490148)
interface __BaseEnv_Env {
  SESSION: KVNamespace
  AFFILIATE_DB: D1Database
  IMAGES: ImagesBinding
  ASSETS: Fetcher
  AFFILIATE_BATCH_LIMIT: '25'
  AFFILIATE_CHAIN_ID: '80002'
  AFFILIATE_CONFIRMATIONS: '64'
  AFFILIATE_DATA_API_URL: 'https://data-api.kuest.com'
  AFFILIATE_DEPOSIT_WALLET_FACTORY: '0x2CcdC6C5dDcd895aFcCD259F291de9b618A5cA6c'
  AFFILIATE_KUEST_FEE_RECEIVER: '0x645E67CC15DAE4F312dc941fA190c52E7d598c67'
  AFFILIATE_MAX_ATTEMPTS: '8'
  AFFILIATE_MAX_HISTORY_PAGES: '20'
  AFFILIATE_RPC_URL: 'https://polygon-amoy.drpc.org'
  AFFILIATE_START_BLOCK: '42753000'
  AFFILIATE_DRY_RUN: 'true'
  AFFILIATE_TOKEN_DECIMALS: '6'
  GITHUB_APP_URL: 'https://github-app.kuest.com'
  KUEST_CHAIN_MODE: 'amoy'
  PROTOCOL_PITCH_DECK_TO_EMAIL: 'hello@kuest.com'
  RATE_LIMIT_DOMAIN_MAX: '90'
  RATE_LIMIT_DOMAIN_REGISTER_MAX: '600'
  RATE_LIMIT_LAUNCH_MAX: '30'
  RATE_LIMIT_PROTOCOL_DECK_MAX: '12'
  RATE_LIMIT_REOWN_CONNECTION_MAX: '240'
  RATE_LIMIT_SUPABASE_RESOURCES_MAX: '240'
  RATE_LIMIT_VERCEL_CONNECTION_MAX: '240'
  RATE_LIMIT_WINDOW_MS: '600000'
  RESEND_FROM_EMAIL: 'Kuest <hello@kuest.com>'
  SITE_URL: 'https://kuest.com'
  REOWN_APPKIT_PROJECT_ID: string
  RESEND_API_KEY: string
  DUB_API_KEY: string
  SUPABASE_ANON_KEY: string
  SUPABASE_SERVICE_ROLE_KEY: string
  SUPABASE_URL: string
  VERCEL_OAUTH_CLIENT_ID: string
  VERCEL_OAUTH_CLIENT_SECRET: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/worker')
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'AFFILIATE_BATCH_LIMIT'
      | 'AFFILIATE_CHAIN_ID'
      | 'AFFILIATE_CONFIRMATIONS'
      | 'AFFILIATE_DATA_API_URL'
      | 'AFFILIATE_DEPOSIT_WALLET_FACTORY'
      | 'AFFILIATE_KUEST_FEE_RECEIVER'
      | 'AFFILIATE_MAX_ATTEMPTS'
      | 'AFFILIATE_MAX_HISTORY_PAGES'
      | 'AFFILIATE_RPC_URL'
      | 'AFFILIATE_START_BLOCK'
      | 'AFFILIATE_DRY_RUN'
      | 'AFFILIATE_TOKEN_DECIMALS'
      | 'GITHUB_APP_URL'
      | 'KUEST_CHAIN_MODE'
      | 'PROTOCOL_PITCH_DECK_TO_EMAIL'
      | 'RATE_LIMIT_DOMAIN_MAX'
      | 'RATE_LIMIT_DOMAIN_REGISTER_MAX'
      | 'RATE_LIMIT_LAUNCH_MAX'
      | 'RATE_LIMIT_PROTOCOL_DECK_MAX'
      | 'RATE_LIMIT_REOWN_CONNECTION_MAX'
      | 'RATE_LIMIT_SUPABASE_RESOURCES_MAX'
      | 'RATE_LIMIT_VERCEL_CONNECTION_MAX'
      | 'RATE_LIMIT_WINDOW_MS'
      | 'RESEND_FROM_EMAIL'
      | 'SITE_URL'
      | 'REOWN_APPKIT_PROJECT_ID'
      | 'RESEND_API_KEY'
      | 'DUB_API_KEY'
      | 'SUPABASE_ANON_KEY'
      | 'SUPABASE_SERVICE_ROLE_KEY'
      | 'SUPABASE_URL'
      | 'VERCEL_OAUTH_CLIENT_ID'
      | 'VERCEL_OAUTH_CLIENT_SECRET'
    >
  > {}
}
